blank_issues_enabled: false
contact_links:
  - name: Ory Ory Hydra PHP Client Forum
    url: https://github.com/ory/hydra-client-php/discussions
    about: Please ask and answer questions here, show your implementations and discuss ideas.
  - name: Ory Chat
    url: https://www.ory.sh/chat
    about: Hang out with other Ory community members to ask and answer questions.
  - name: Ory Support for Business
    url: https://github.com/ory/open-source-support/blob/master/README.md
    about: Buy professional support for Ory Ory Hydra PHP Client.
