<?php
/**
 * CertificateTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ory\Hydra\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ORY Hydra
 *
 * Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Ory\Hydra\Client;

use PHPUnit\Framework\TestCase;

/**
 * CertificateTest Class Doc Comment
 *
 * @category    Class
 * @description Certificate
 * @package     Ory\Hydra\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CertificateTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Certificate"
     */
    public function testCertificate()
    {
    }

    /**
     * Test attribute "authorityKeyId"
     */
    public function testPropertyAuthorityKeyId()
    {
    }

    /**
     * Test attribute "basicConstraintsValid"
     */
    public function testPropertyBasicConstraintsValid()
    {
    }

    /**
     * Test attribute "cRLDistributionPoints"
     */
    public function testPropertyCRLDistributionPoints()
    {
    }

    /**
     * Test attribute "dNSNames"
     */
    public function testPropertyDNSNames()
    {
    }

    /**
     * Test attribute "emailAddresses"
     */
    public function testPropertyEmailAddresses()
    {
    }

    /**
     * Test attribute "excludedDNSDomains"
     */
    public function testPropertyExcludedDNSDomains()
    {
    }

    /**
     * Test attribute "excludedEmailAddresses"
     */
    public function testPropertyExcludedEmailAddresses()
    {
    }

    /**
     * Test attribute "excludedIPRanges"
     */
    public function testPropertyExcludedIPRanges()
    {
    }

    /**
     * Test attribute "excludedURIDomains"
     */
    public function testPropertyExcludedURIDomains()
    {
    }

    /**
     * Test attribute "extKeyUsage"
     */
    public function testPropertyExtKeyUsage()
    {
    }

    /**
     * Test attribute "extensions"
     */
    public function testPropertyExtensions()
    {
    }

    /**
     * Test attribute "extraExtensions"
     */
    public function testPropertyExtraExtensions()
    {
    }

    /**
     * Test attribute "iPAddresses"
     */
    public function testPropertyIPAddresses()
    {
    }

    /**
     * Test attribute "isCA"
     */
    public function testPropertyIsCA()
    {
    }

    /**
     * Test attribute "issuer"
     */
    public function testPropertyIssuer()
    {
    }

    /**
     * Test attribute "issuingCertificateURL"
     */
    public function testPropertyIssuingCertificateURL()
    {
    }

    /**
     * Test attribute "keyUsage"
     */
    public function testPropertyKeyUsage()
    {
    }

    /**
     * Test attribute "maxPathLen"
     */
    public function testPropertyMaxPathLen()
    {
    }

    /**
     * Test attribute "maxPathLenZero"
     */
    public function testPropertyMaxPathLenZero()
    {
    }

    /**
     * Test attribute "notBefore"
     */
    public function testPropertyNotBefore()
    {
    }

    /**
     * Test attribute "oCSPServer"
     */
    public function testPropertyOCSPServer()
    {
    }

    /**
     * Test attribute "permittedDNSDomains"
     */
    public function testPropertyPermittedDNSDomains()
    {
    }

    /**
     * Test attribute "permittedDNSDomainsCritical"
     */
    public function testPropertyPermittedDNSDomainsCritical()
    {
    }

    /**
     * Test attribute "permittedEmailAddresses"
     */
    public function testPropertyPermittedEmailAddresses()
    {
    }

    /**
     * Test attribute "permittedIPRanges"
     */
    public function testPropertyPermittedIPRanges()
    {
    }

    /**
     * Test attribute "permittedURIDomains"
     */
    public function testPropertyPermittedURIDomains()
    {
    }

    /**
     * Test attribute "policyIdentifiers"
     */
    public function testPropertyPolicyIdentifiers()
    {
    }

    /**
     * Test attribute "publicKey"
     */
    public function testPropertyPublicKey()
    {
    }

    /**
     * Test attribute "publicKeyAlgorithm"
     */
    public function testPropertyPublicKeyAlgorithm()
    {
    }

    /**
     * Test attribute "raw"
     */
    public function testPropertyRaw()
    {
    }

    /**
     * Test attribute "rawIssuer"
     */
    public function testPropertyRawIssuer()
    {
    }

    /**
     * Test attribute "rawSubject"
     */
    public function testPropertyRawSubject()
    {
    }

    /**
     * Test attribute "rawSubjectPublicKeyInfo"
     */
    public function testPropertyRawSubjectPublicKeyInfo()
    {
    }

    /**
     * Test attribute "rawTBSCertificate"
     */
    public function testPropertyRawTBSCertificate()
    {
    }

    /**
     * Test attribute "serialNumber"
     */
    public function testPropertySerialNumber()
    {
    }

    /**
     * Test attribute "signature"
     */
    public function testPropertySignature()
    {
    }

    /**
     * Test attribute "signatureAlgorithm"
     */
    public function testPropertySignatureAlgorithm()
    {
    }

    /**
     * Test attribute "subject"
     */
    public function testPropertySubject()
    {
    }

    /**
     * Test attribute "subjectKeyId"
     */
    public function testPropertySubjectKeyId()
    {
    }

    /**
     * Test attribute "uRIs"
     */
    public function testPropertyURIs()
    {
    }

    /**
     * Test attribute "unhandledCriticalExtensions"
     */
    public function testPropertyUnhandledCriticalExtensions()
    {
    }

    /**
     * Test attribute "unknownExtKeyUsage"
     */
    public function testPropertyUnknownExtKeyUsage()
    {
    }

    /**
     * Test attribute "version"
     */
    public function testPropertyVersion()
    {
    }
}
