<?php
/**
 * ExtensionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ory\Hydra\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ORY Hydra
 *
 * Welcome to the ORY Hydra HTTP API documentation. You will find documentation for all HTTP APIs here.
 *
 * The version of the OpenAPI document: latest
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Ory\Hydra\Client;

use PHPUnit\Framework\TestCase;

/**
 * ExtensionTest Class Doc Comment
 *
 * @category    Class
 * @description Extension Extension Extension Extension represents the ASN.1 structure of the same name. See RFC 5280, section 4.2.
 * @package     Ory\Hydra\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ExtensionTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Extension"
     */
    public function testExtension()
    {
    }

    /**
     * Test attribute "critical"
     */
    public function testPropertyCritical()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "value"
     */
    public function testPropertyValue()
    {
    }
}
